package(default_visibility = ["//src:__subpackages__"])


cc_library(
    name = "g_storage_utils",
    srcs = ["g_storage_utils.cc"],
    hdrs = ["g_storage_utils.h"],
    deps = [
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@google_cloud_cpp//:storage",
    ],
)
